### PR TITLE
Completed project layout

### PR DESCRIPTION
**Pull request by Kyle-Law**
Completed clone of https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0.
Created by @Kyle-Law  and @mbabaliiryn. We used HTML and CSS to clone the project. The website clone is done with a smooth ride. HTML and Stickler bugs have been cleared. Please check :)

### CODE REVIEW

**Comment by pelzolga123** [comment]
### Hi Team, 
### I am marking this Pull request as invalid due to following reasons:
* Your README.md file is empty.
* Pull Request doesn't short summary.

### Please fix above issues and submit new code review request.
If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Kyle-Law** [comment]
Hi @pelzolga123 , thank you for reviewing our project, your recommendations have been implemented :)

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi team nice work,

But there are just few changes to make :slightly_smiling_face: 

- [x] About using semantic html, wrap your navigation section within your header with a **```nav tag```**.

- [x] This image should be centered, but on my screen it is not, kindly look into.

Screenshot from 2020-01-21 14-13-43



- [x] The font size of  **```Space Ripples Reveal Big Bang’s Smoking Gun```** should be adjusted.

- [x] Wrap the image tag on line 24 in your index.html file with a link tag ``` <a></a>``` [test it out on the page ](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0).
- [x] Footer, should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

  After implementing these changes, submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

**Comment by Kyle-Law** [comment]
@uche-inyama Thank you! Your recommendations have been implemented, the latest Stickler bugs have fixed,  and README.md has been updated with the latest live link.
Looking forward to another review from TSEs! :)

**Review by mosesogwo — APPROVED** [review]
**Hi @Kyle-Law, @mbabaliiryn, :trophy:you have done well.**

Your project is approved!

**Optional (since you have come this far with the project):**
> You were expected to use **float** (check pathwright) for all alignments on the page, but you have used css grid in most places.
.
You may consider changing your alignments to use float before merging.

**Happy coding! :smile:**

#### Status: Approved!

**Comment by Kyle-Law** [comment]
@mosesogwo Thank you for reviewing our codes! :)

**Pull request merged**
